title: "Kristy Mualim"
name: "Kristy Mualim"
url: "https://kmualim.github.io"
baseurl: ""
repository: "kmualim/kmualim.github.io"
description: "PhD Student, UC Berkeley"

locale: "en-US"
encoding: "utf-8"
timezone: America/Los_Angeles

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /:categories/:title/

gems:
  - jekyll-sitemap
  - jekyll-feed
